return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    opts = {
      -- flavour = "auto",
      -- configuration options...
      integrations = {
        blink_cmp = true,
        indent_blankline = {
          enabled = true,
          scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
          colored_indent_levels = false,
        },
        noice = true,
        snacks = {
          enabled = true,
          indent_scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
        },
      },
      transparent_background = false,
      background = {
        dark = "mocha",
        light = "latte",
      },
      color_overrides = {
        mocha = {
          rosewater = "#ffb59d",
          -- flamingo = "#ffb59d",
          pink = "#fbb0d8",
          mauve = "#c9bfff",
          red = "#fbb0d8",
          maroon = "#fbb0d8",
          peach = "#ffb59d",
          yellow = "#d5c871",
          green = "#d9bde3",
          teal = "#91d5ad",
          sky = "#a4c9fe",
          sapphire = "#a5c8ff",
          blue = "#a4c9fe",
          lavender = "#a4c9fe",
          text = "#e1e2e9",
          subtext1 = "#cccccc",
          subtext0 = "#bbbbbb",
          overlay2 = "#aaaaaa",
          overlay1 = "#999999",
          overlay0 = "#888888",
          surface2 = "#777777",
          surface1 = "#666666",
          surface0 = "#555555",
          -- surface0 = "#bcc7db",
          base = "#111318",
          mantle = "#111318",
          crust = "#111318",
        },
        latte = {
          rosewater = "#ffb59d",
          -- flamingo = "#ffb59d",
          pink = "#fbb0d8",
          mauve = "#c9bfff",
          red = "#fbb0d8",
          maroon = "#fbb0d8",
          peach = "#ffb59d",
          yellow = "#d5c871",
          green = "#d9bde3",
          teal = "#91d5ad",
          sky = "#a4c9fe",
          sapphire = "#a5c8ff",
          blue = "#a4c9fe",
          lavender = "#a4c9fe",
          text = "#e1e2e9",
          -- 明亮配色
          subtext1 = "#555555",
          subtext0 = "#666666",
          overlay2 = "#777777",
          overlay1 = "#888888",
          overlay0 = "#999999",
          surface2 = "#aaaaaa",
          surface1 = "#bbbbbb",
          surface0 = "#cccccc",
          base = "#111318",
          mantle = "#111318",
          crust = "#111318",
        },
      },
    },
  },
}
