return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    -- flavour = "auto",
    -- configuration options...
    integrations = {
      blink_cmp = true,
      indent_blankline = {
        enabled = true,
        scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
        colored_indent_levels = false,
      },
      noice = true,
      snacks = {
        enabled = true,
        indent_scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
      },
    },
    transparent_background = false,
    background = {
      dark = "mocha",
      light = "latte",
    },
    color_overrides = {
      mocha = {
        rosewater = "{{colors.orange.default.hex}}",
        flamingo = "{{colors.orange.default.hex}}",
        pink = "{{colors.red.default.hex}}",
        mauve = "{{colors.purple.default.hex}}",
        red = "{{colors.red.default.hex}}",
        maroon = "{{colors.red.default.hex}}",
        peach = "{{colors.orange_source.default.hex}}",
        yellow = "{{colors.yellow.default.hex}}",
        green = "{{colors.tertiary.default.hex}}",
        teal = "{{colors.green.default.hex}}",
        sky = "{{colors.primary.default.hex}}",
        sapphire = "{{colors.primary.default.hex}}",
        blue = "{{colors.primary.default.hex}}",
        lavender = "{{colors.primary.default.hex}}",
        text = "{{colors.primary.default.hex}}",
        subtext1 = "#bbbbbb",
        subtext0 = "#aaaaaa",
        overlay2 = "{{colors.secondary.default.hex}}",
        overlay1 = "#888888",
        overlay0 = "#777777",
        surface2 = "#666666",
        surface1 = "#555555",
        surface0 = "#444444",
        base = "{{colors.surface.default.hex}}",
        mantle = "{{colors.surface.default.hex}}",
        crust = "{{colors.surface.default.hex}}",
      },
      latte = {
        rosewater = "{{colors.orange_source.default.hex}}",
        flamingo = "{{colors.orange_source.default.hex}}",
        pink = "{{colors.red_source.default.hex}}",
        mauve = "{{colors.purple.default.hex}}",
        red = "{{colors.red_source.default.hex}}",
        maroon = "{{colors.red_source.default.hex}}",
        peach = "{{colors.orange_source.default.hex}}",
        yellow = "{{colors.yellow_container.default.hex}}",
        green = "{{colors.tertiary.default.hex}}",
        teal = "{{colors.green_source.default.hex}}",
        sky = "{{colors.primary.default.hex}}",
        sapphire = "{{colors.primary.default.hex}}",
        blue = "{{colors.primary.default.hex}}",
        lavender = "{{colors.primary.default.hex}}",
        text = "{{colors.primary.default.hex}}",
        subtext1 = "#555555",
        subtext0 = "#666666",
        overlay2 = "{{colors.secondary.default.hex}}",
        overlay1 = "#888888",
        overlay0 = "#999999",
        surface2 = "#aaaaaa",
        surface1 = "#bbbbbb",
        surface0 = "#cccccc",
        base = "{{colors.surface.default.hex}}",
        mantle = "{{colors.surface.default.hex}}",
        crust = "{{colors.surface.default.hex}}",
      },
    },
    highlight_overrides = {
      mocha = function(mocha)
        return {
          NormalFloat = { fg = mocha.sky },
        }
      end,
    },
  },
}
